public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        byte b = 100;
        System.out.println("Значение переменной b" + " с типом byte" + " равно " + b);
        short s = 230;
        System.out.println("Значение переменной s" + " с типом short" + " равно " + s);
        int i = 300;
        System.out.println("Значение переменной i" + " с типом int" + " равно " + i);
        long l = 500L;
        System.out.println("Значение переменной l" + " с типом long" + " равно " + l);
        float f = 3.143f;
        System.out.println("Значение переменной f" + " с типом float" + " равно " + f);
        double d = 5.143143143;
        System.out.println("Значение переменной d" + " с типом double" + " равно " + d);
        System.out.println("Задача 2");
        float a = 27.12f;
        System.out.println(a);
        long с = 987678965549L;
        System.out.println(с);
        double e = 2.786;
        System.out.println(e);
        short g = 569;
        System.out.println(g);
        short h = -159;
        System.out.println(h);
        int j = 27897;
        System.out.println(j);
        byte k = 67;
        System.out.println(k);
        System.out.println("Задача 3");
        byte lP = 23;
        byte aS = 27;
        byte eA = 30;
        int totalStudents = lP + aS + eA;
        short totalSheets = 480;
        int everyStudent = totalSheets / totalStudents;
        System.out.println("На каждого ученика рассчитано " + everyStudent + " листов бумаги");
        System.out.println("Задача 4");
        byte sixteenBottles = 16;
        byte twoMinutes = 2;
        int oneMinutes = sixteenBottles / twoMinutes;
        System.out.println("Считаем, что за одну минуту машина производит " + oneMinutes + " бутылок");
        int w = 20;
        int x = 1440;
        System.out.println("В одном дне - " + x + " минут");
        int y = 4320;
        System.out.println("В трех днях - " + y + " минут");
        int z = 44640;
        System.out.println("В одном месяце - " + z + " минут");
        System.out.println("Исходя из этого:");
        int twentyMinutes = oneMinutes * w;
        int day = oneMinutes * x;
        int threeDay = oneMinutes * y;
        int month = oneMinutes * z;
        System.out.println("За" + " 20 минут машина произвела " + twentyMinutes + " штук бытылок");
        System.out.println("За" + " сутки машина произвела " + day + " штук бытылок");
        System.out.println("За" + " 3 дня машина произвела " + threeDay + " штук бытылок");
        System.out.println("За" + " 1 месяц машина произвела " + month + " штук бытылок");
        System.out.println("Задача 5");
        byte totalCans = 120;
        byte whiteCans = 2;
        byte brownCans = 4;
        int oneClass = whiteCans + brownCans;
        System.out.println("На один класс нужно " + oneClass + " банок краски");
        int totalClassec = totalCans / oneClass;
        System.out.println("Всего в школе " + totalClassec + " классов");
        System.out.println("Исходя из условия, на один класс требуется 2 белой и 4 коричневой банок краски");
        int allWhite = whiteCans * totalClassec;
        int allBrown = brownCans * totalClassec;
        System.out.println("В школе, где " + totalClassec + " классов, нужно " + allWhite + " банок белой краски и " + allBrown + " банок коричневой краски");
        System.out.println("Задача 6");
        int bananas = 5;
        int milk = 2;
        int iceCream = 2;
        int eggs = 4;
        int oneBananas = 80;
        int oneMilk = 105;
        int oneIceCream = 100;
        int oneEgg = 70;
        int bananaWeiht = bananas * oneBananas;
        System.out.println("Общий вес бананов " + bananaWeiht + " грамм");
        int milkWeiht = milk * oneMilk;
        System.out.println("Общий вес молока " + milkWeiht + " грамм");
        int iceCreamWeiht = iceCream * oneIceCream;
        System.out.println("Общий вес мороженого " + iceCreamWeiht + " грамм");
        int eggsWeiht = eggs * oneEgg;
        System.out.println("Общий вес яиц " + eggsWeiht + " грамм");
        System.out.println("Переводим в килограммы");
        double kg = 1000;
        double kgBanana = bananaWeiht / kg;
        System.out.println("Общий вес бананов в кг = " + kgBanana);
        double kgMilk = milkWeiht / kg;
        System.out.println("Общий вес молока в кг = " + kgMilk);
        double kgIceCream = iceCreamWeiht / kg;
        System.out.println("Общий вес мороженого в кг = " + kgIceCream);
        double kgEgg = eggsWeiht / kg;
        System.out.println("Общий вес яиц в кг = " + kgEgg);
        int totalGr = bananaWeiht + milkWeiht + iceCreamWeiht +eggsWeiht;
        double totalKg = kgBanana + kgMilk + kgIceCream + kgEgg;
        System.out.println("Итого");
        System.out.println("Общий вес завтрака спортсмена = " + totalGr + " грамм, или " + totalKg + " килограмм");
        System.out.println("Задача 7");
        System.out.println("Переводим кг в граммы");
        int kG = 1000;
        int weight = 7;
        int gWeight = (int) (kg * weight);
        System.out.println("Вес который надо сбросить = " + gWeight + " грамм");
        int twoHundredFifty = 250;
        int fiveHungred = 500;
        int first = gWeight / twoHundredFifty;
        int second = gWeight / fiveHungred;
        System.out.println("Если в день терять по 250 грамм, спортсмену понадобится " + first + " дней");
        System.out.println("Если в день терять по 500 грамм, спортсмену понадобится " + second + " дней");
        int weightCategories = 2;
        int average = (first + second) / 2;
        System.out.println("В среднем понадобится " + average + " день, чтобы добиться результата похудения");
        System.out.println("Задача 8");
        int masha = 67760;
        int denis = 83690;
        int kris = 76230;
        byte year = 12;
        double mYear = masha * year;
        double dYear = denis * year;
        double kYear = kris * year;
        double percent = 0.1;
        double profitM = masha * percent + masha;
        double profitD = denis * percent + denis;
        double profitK = kris * percent + kris;
        double newYearM = profitM * year;
        double newYearD = profitD * year;
        double newYearK = profitK * year;
        double profitDifferenceM = newYearM - mYear;
        double profitDifferenceD = newYearD - dYear;
        double profitDifferenceK = newYearK - kYear;
        System.out.println("Маша теперь получает " + profitM + " рублей. Годовой доход вырос на " + profitDifferenceM + " рублей");
        System.out.println("Денис теперь получает " + profitD + " рублей. Годовой доход вырос на " + profitDifferenceD + " рублей");
        System.out.println("Кристина теперь получает " + profitK + " рублей. Годовой доход вырос на " + profitDifferenceK + " рублей");


    }
}
